module.exports = {
    plugins: [
      // enable a built-in plugin by name      
        "removeDoctype",
        "removeXMLProcInst",
        "removeComments",
        "removeMetadata",
        "removeXMLNS",
        "removeEditorsNSData",
        "cleanupAttrs",
        "inlineStyles",
        "minifyStyles",
        "convertStyleToAttrs",
        "cleanupIDs",
        "removeRasterImages",
        "removeUselessDefs",
        "cleanupNumericValues",
        "cleanupListOfValues",
        "convertColors",
        "removeUnknownsAndDefaults",
        "removeNonInheritableGroupAttrs",
        "removeUselessStrokeAndFill",
        "removeViewBox",
        "cleanupEnableBackground",
        "removeHiddenElems",
        "removeEmptyText",
        "convertShapeToPath",
        "moveElemsAttrsToGroup",
        "moveGroupAttrsToElems",
        "collapseGroups",
        "convertPathData",
        "convertEllipseToCircle",
        "convertTransform",
        "removeEmptyAttrs",
        "removeEmptyContainers",
        "mergePaths",
        "removeUnusedNS",
        "reusePaths",
        "sortAttrs",
        "sortDefsChildren",
        "removeTitle",
        "removeDesc",
        "removeDimensions",
        "removeStyleElement",
        "removeScriptElement"
    ]
  }
  